### ISSUE TITLE
web_docroot

### ISSUE THREAD

**Issue by ultimike** [pantheon-systems/terminus-quicksilver-plugin#10]
When working with a site that is using webdocroot, this plugin installs the scripts in the project root's "private" directory, not the web/private directory.

Seems like the quicksilver:install command should check the web_docroot value in an existing pantheon.yml and act accordingly.

-mike

**Comment by greg-1-anderson** [comment]
Fixed in 1.1.1 of the Terminus Quicksilver Plugin.

Thanks.
