### ISSUE TITLE
FEATURE Quicksilver install all

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/terminus-quicksilver-plugin#2]
If I specify my own quicksilver repository on github, I want the option to install the whole thing instead of one directory at a time. This subcommand would use a complete `pantheon.yml` in the repo root instead of the snippets embedded in the readme in each directory, and would get each script.

**Comment by greg-1-anderson** [comment]
Fixed via `terminus quicksilver profile <name>` command.
