### ISSUE TITLE
-bash: quicksilver-cli: command not found

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/terminus-quicksilver-plugin#5]
Following a successful installation with composer, the quicksilver-cli command is not found.

"Ensure that ~/.composer/vendor/bin is in your global $PATH." 

`Taras-MacBook-Pro:hello-my-drupal tararowell$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.composer/vendor/bin:/opt/X11/bin:/Applications/DevDesktop/drush`

`/Users/tararowell/.quicksilver/quicksilver.yml` contents

```
# Quicksilver configuration file
#
# Copy to $HOME/.quicksilver/quicksilver.yml
#
repositories:
  slack_notification: https://github.com/pantheon-systems/quicksilver-examples
```

**Comment by greg-1-anderson** [comment]
Bad instructions. The ~ cannot literally appear in your $PATH; you must put in a full path.

This project is being ported to a terminus plugin, so it will be easier to install and use.

**Comment by greg-1-anderson** [comment]
This project has now been converted to a terminus plugin, so this should not be an issue any longer.
