### ISSUE TITLE
Use a --site parameter or detect if not in the right context

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/terminus-quicksilver-plugin#7]
My first guess when setting this up is that it would work directly with my sites on Pantheon. I didn't expect that it would require a local clone, and was confused when it just put a `pantheon.yml` file in my home directory.

If we're going to make it require a local working copy, we should probably put some safeguards in place and check that the current working directory is the root of a valid Git repo before doing anything. We can even provide informative instructions if not.

Alternatively, we could also operate over SFTP mode and do the commits remotely. That's probably more work.

**Comment by greg-1-anderson** [comment]
The first half of this issue -- to detect if there is a site in the context of the cwd -- has been implemented.

I have considered remote operation of this tool, and may attempt that at some point, but it's not on my roadmap at the moment.
